= SAÉ 3.01 2022-2023
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/sae3-01-template

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

toc::[]

== Equipe

Projet est réalisé par::

- https://github.com/Geriandre[DE BEAUMONT Pierre]
- https://github.com/Aestraa[MOINY-BOUDGHASSEM Yanis]
- https://github.com/Hepssylon[NAUD Lilian]
- https://github.com/Ozouka[ZOULI-BARRERE Karim] 


Tuteur/tutrice enseignant(e) de l'équipe:: mailto:amelie.legrand@univ-tlse2.fr[ALE, blabla]

== Réalisations 

TIP: Mettez ici toutes les informations nécessaire à l'utilisation de votre dépôt (comment on installe votre application, où sont les docs, etc.)

[cols="1,2,2",options=header]
|===
| Date    | Nom         |  Lien                            
| 21/11   | Documentation Utilisateur    |https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-1/blob/master/Documentation/Utilisateur/DocUtilisateur.adoc
| 21/11   | Documentation Technique      |https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-1/blob/master/Documentation/Technique/DocTechnique.adoc
|===


== Gestion de projet & Qualité      


=== Évaluations hebdomadaires

NOTE: Les notes ci-dessous sont mises à jour directement par les enseignants responsables de la compétence 5.

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTc3HJJ9iSI4aa2I9a567wX1AUEmgGrQsPl7tHGSAJ_Z-lzWXwYhlhcVIhh5vCJxoxHXYKjSLetP6NS/pubchart?oid=1850914734&amp;format=image"></iframe>
++++
endif::[]
